# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/elisa-c/DetailsPodSpecs.git'

target 'CriptoBeca' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CriptoBeca
  pod 'Reusable'
  pod 'SwiftLint'
  pod 'AlamofireImage', '~> 3.4.0'
  pod 'DetailsLibrary', '~> 0.1.0'
  
  target 'CriptoBecaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CriptoBecaUITests' do
    # Pods for testing
  end

end
